spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/baza-wypozyczenia
    username: postgres
    password: postgres
    continueOnError: true
    initialize: false

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: create-drop
        temp:
          use_jdbc_metadata_defaults: false

